name:                optimal-hs-accelerate-pbil
version:             1.1.0.0
github:              "JustinLovinger/optimal-hs-accelerate-pbil"
license:             MIT
author:              "Justin Lovinger"
maintainer:          "git@justinlovinger.com"
copyright:           "Justin Lovinger"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Run PBIL derivative-free (metaheuristic) optimization backed by Accelerate.
category:            optimization

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JustinLovinger/optimal-hs-accelerate-pbil#readme>

ghc-options:
  -Wall

dependencies:
  - accelerate >= 1.3 && < 2
  - base >= 4.7 && < 5
  - mwc-random-accelerate >= 0.2 && < 0.3
  - sfc-random-accelerate >= 0.1 && < 0.2

library:
  source-dirs: src

tests:
  optimal-hs-accelerate-pbil-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - hspec
      - optimal-hs-accelerate-pbil
      - random >= 1.1
